<?php
/**
 * ConvertApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stirling PDF - Processing API
 *
 * API documentation for PDF processing operations including conversion, manipulation, security, and utilities. Please note all requests require authentication and as such should have a 'X-API-KEY' provided in their header
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: contact@stirlingpdf.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConvertApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConvertApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for convertEmlToPdf
     *
     * Convert EML to PDF.
     *
     */
    public function testConvertEmlToPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for convertToImage
     *
     * Convert PDF to image(s).
     *
     */
    public function testConvertToImage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for convertToPdf
     *
     * Convert images to a PDF file.
     *
     */
    public function testConvertToPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for htmlToPdf
     *
     * Convert an HTML or ZIP (containing HTML and CSS) to PDF.
     *
     */
    public function testHtmlToPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for markdownToPdf
     *
     * Convert a Markdown file to PDF.
     *
     */
    public function testMarkdownToPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pdfToCsv
     *
     * Extracts a CSV document from a PDF.
     *
     */
    public function testPdfToCsv()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pdfToPdfA
     *
     * Convert a PDF to a PDF/A.
     *
     */
    public function testPdfToPdfA()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processFileToPDF
     *
     * Convert a file to a PDF using LibreOffice.
     *
     */
    public function testProcessFileToPDF()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPdfToHTML
     *
     * Convert PDF to HTML.
     *
     */
    public function testProcessPdfToHTML()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPdfToMarkdown
     *
     * Convert PDF to Markdown.
     *
     */
    public function testProcessPdfToMarkdown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPdfToPresentation
     *
     * Convert PDF to Presentation format.
     *
     */
    public function testProcessPdfToPresentation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPdfToRTForTXT
     *
     * Convert PDF to Text or RTF format.
     *
     */
    public function testProcessPdfToRTForTXT()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPdfToWord
     *
     * Convert PDF to Word document.
     *
     */
    public function testProcessPdfToWord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPdfToXML
     *
     * Convert PDF to XML.
     *
     */
    public function testProcessPdfToXML()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for urlToPdf
     *
     * Convert a URL to a PDF.
     *
     */
    public function testUrlToPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
