<?php
/**
 * GeneralApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stirling PDF - Processing API
 *
 * API documentation for PDF processing operations including conversion, manipulation, security, and utilities. Please note all requests require authentication and as such should have a 'X-API-KEY' provided in their header
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: contact@stirlingpdf.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GeneralApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GeneralApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for autoSplitPdf1
     *
     * Auto split PDF pages into separate documents based on size or count.
     *
     */
    public function testAutoSplitPdf1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createBookletImposition
     *
     * Create a booklet with proper page imposition.
     *
     */
    public function testCreateBookletImposition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cropPdf
     *
     * Crops a PDF document.
     *
     */
    public function testCropPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePages
     *
     * Remove pages from a PDF file.
     *
     */
    public function testDeletePages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editTableOfContents
     *
     * Edit Table of Contents.
     *
     */
    public function testEditTableOfContents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extractBookmarks
     *
     * Extract PDF Bookmarks.
     *
     */
    public function testExtractBookmarks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mergeMultiplePagesIntoOne
     *
     * Merge multiple pages of a PDF document into a single page.
     *
     */
    public function testMergeMultiplePagesIntoOne()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mergePdfs
     *
     * Merge multiple PDF files into one.
     *
     */
    public function testMergePdfs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for overlayPdfs
     *
     * Overlay PDF files in various modes.
     *
     */
    public function testOverlayPdfs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pdfToSinglePage
     *
     * Convert a multi-page PDF into a single long page PDF.
     *
     */
    public function testPdfToSinglePage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rearrangePages
     *
     * Rearrange pages in a PDF file.
     *
     */
    public function testRearrangePages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeImages
     *
     * Remove images from file to reduce the file size..
     *
     */
    public function testRemoveImages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rotatePDF
     *
     * Rotate a PDF file.
     *
     */
    public function testRotatePDF()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scalePages
     *
     * Change the size of a PDF page/document.
     *
     */
    public function testScalePages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for splitPdf
     *
     * Split PDF pages into smaller sections.
     *
     */
    public function testSplitPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for splitPdf1
     *
     * Split PDFs by Chapters.
     *
     */
    public function testSplitPdf1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for splitPdf2
     *
     * Split a PDF file into separate documents.
     *
     */
    public function testSplitPdf2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
