<?php
/**
 * MiscApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stirling PDF - Processing API
 *
 * API documentation for PDF processing operations including conversion, manipulation, security, and utilities. Please note all requests require authentication and as such should have a 'X-API-KEY' provided in their header
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: contact@stirlingpdf.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MiscApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MiscApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addAttachments
     *
     * Add attachments to PDF.
     *
     */
    public function testAddAttachments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addPageNumbers
     *
     * Add page numbers to a PDF document.
     *
     */
    public function testAddPageNumbers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addStamp
     *
     * Add stamp to a PDF file.
     *
     */
    public function testAddStamp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for autoSplitPdf
     *
     * Auto split PDF pages into separate documents.
     *
     */
    public function testAutoSplitPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for decompressPdf
     *
     * Decompress PDF streams.
     *
     */
    public function testDecompressPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extractHeader
     *
     * Grabs all JS from a PDF and returns a single JS file with all code.
     *
     */
    public function testExtractHeader()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extractHeader1
     *
     * Extract header from PDF file.
     *
     */
    public function testExtractHeader1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extractImageScans
     *
     * Extract image scans from an input file.
     *
     */
    public function testExtractImageScans()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extractImages
     *
     * Extract images from a PDF file.
     *
     */
    public function testExtractImages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for flatten
     *
     * Flatten PDF form fields or full page.
     *
     */
    public function testFlatten()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for metadata
     *
     * Update metadata of a PDF file.
     *
     */
    public function testMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for optimizePdf
     *
     * Optimize PDF file.
     *
     */
    public function testOptimizePdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for overlayImage
     *
     * Overlay image onto a PDF file.
     *
     */
    public function testOverlayImage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPdfWithOCR
     *
     * Process a PDF file with OCR.
     *
     */
    public function testProcessPdfWithOCR()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeBlankPages
     *
     * Remove blank pages from a PDF file.
     *
     */
    public function testRemoveBlankPages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for repairPdf
     *
     * Repair a PDF file.
     *
     */
    public function testRepairPdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceAndInvertColor
     *
     * Replace-Invert Color PDF.
     *
     */
    public function testReplaceAndInvertColor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scannerEffect
     *
     * Apply scanner effect to PDF.
     *
     */
    public function testScannerEffect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unlockPDFForms
     *
     * Remove read-only property from form fields.
     *
     */
    public function testUnlockPDFForms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
